// <auto-generated />
using System;
using Backend.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(StockVaultContext))]
    [Migration("20260423111426_Fixed_RelationShip_Between_Schedules_Cycles_2")]
    partial class Fixed_RelationShip_Between_Schedules_Cycles_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Backend.Entities.AccountLocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonalAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccountId")
                        .IsUnique();

                    b.ToTable("AccountLocks");
                });

            modelBuilder.Entity("Backend.Entities.ContributionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JointAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PayoutCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JointAccountId");

                    b.HasIndex("PayoutCycleId");

                    b.ToTable("ContributionSchedules");
                });

            modelBuilder.Entity("Backend.Entities.JointAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountLockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountLockId");

                    b.HasIndex("UserId");

                    b.ToTable("JointAccounts");
                });

            modelBuilder.Entity("Backend.Entities.JointAccountMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JointAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("JointAccountId", "UserId")
                        .IsUnique();

                    b.ToTable("JointAccountMembers");
                });

            modelBuilder.Entity("Backend.Entities.PayoutCycles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedTotalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JointAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMembersAtStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JointAccountId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("PayoutCycles");
                });

            modelBuilder.Entity("Backend.Entities.PayoutSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaidOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PayoutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("UserId");

                    b.ToTable("PayoutSlots");
                });

            modelBuilder.Entity("Backend.Entities.PersonalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalAccounts");
                });

            modelBuilder.Entity("Backend.Entities.Transection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Transections");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OtpExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PasswordTokenExpiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefreshTokenExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Entities.AccountLocks", b =>
                {
                    b.HasOne("Backend.Entities.PersonalAccount", "PersonalAccount")
                        .WithOne("AccountLock")
                        .HasForeignKey("Backend.Entities.AccountLocks", "PersonalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAccount");
                });

            modelBuilder.Entity("Backend.Entities.ContributionSchedule", b =>
                {
                    b.HasOne("Backend.Entities.JointAccount", "JointAccount")
                        .WithMany()
                        .HasForeignKey("JointAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.PayoutCycles", "PayoutCycle")
                        .WithMany()
                        .HasForeignKey("PayoutCycleId");

                    b.Navigation("JointAccount");

                    b.Navigation("PayoutCycle");
                });

            modelBuilder.Entity("Backend.Entities.JointAccount", b =>
                {
                    b.HasOne("Backend.Entities.AccountLocks", "AccountLock")
                        .WithMany()
                        .HasForeignKey("AccountLockId");

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountLock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.JointAccountMembers", b =>
                {
                    b.HasOne("Backend.Entities.JointAccount", "JointAccount")
                        .WithMany("Members")
                        .HasForeignKey("JointAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JointAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.PayoutCycles", b =>
                {
                    b.HasOne("Backend.Entities.JointAccount", "JointAccount")
                        .WithMany("PayoutCycles")
                        .HasForeignKey("JointAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.ContributionSchedule", "Schedule")
                        .WithMany("PayoutCycles")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JointAccount");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Backend.Entities.PayoutSlot", b =>
                {
                    b.HasOne("Backend.Entities.PayoutCycles", "PayoutCycle")
                        .WithMany("PayoutSlots")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("PayoutSlots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayoutCycle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.PersonalAccount", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("PersonalAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Transection", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("Transections")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.ContributionSchedule", b =>
                {
                    b.Navigation("PayoutCycles");
                });

            modelBuilder.Entity("Backend.Entities.JointAccount", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PayoutCycles");
                });

            modelBuilder.Entity("Backend.Entities.PayoutCycles", b =>
                {
                    b.Navigation("PayoutSlots");
                });

            modelBuilder.Entity("Backend.Entities.PersonalAccount", b =>
                {
                    b.Navigation("AccountLock");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Navigation("PayoutSlots");

                    b.Navigation("PersonalAccounts");

                    b.Navigation("Transections");
                });
#pragma warning restore 612, 618
        }
    }
}
